#!/bin/bash

set -e

usage () {
    echo "Usage:"
}

build () {
    poetry build
}

test () {
    poetry install
    poetry run pytest --cov=momos --cov-report html
}

test_example () {
    poetry install

    cd ./examples/basic/

    mkdir -p doc
    poetry run momos graph -i src/states.c -o doc/states.png --fmt png

    rm -f ./test/test_states.cpp
    poetry run cmake -B build .
    poetry run cmake --build build
    ./build/tests --gmock_catch_leaked_mocks=0

    cd ../../
}

lint () {
    poetry install
    poetry run flake8 momos --ignore=B306
}

publish () {
    poetry publish
}


if [ $# -eq 0 ]
then
    usage
else
    $1
fi
