#!/bin/bash

usage () {
    echo "Usage:"
}

build () {
    poetry build
}

test () {
    poetry install
    poetry run pytest --cov=momos 
}

test_example () {
    cd ./examples/basic/

    poetry run cmake -B build .
    poetry run cmake --build build
    #./build/tests

    cd ../../
}

lint () {
    poetry install
    poetry run flake8 momos
}


if [ $# -eq 0 ]
then
    usage
else
    $1
fi
